# Generated by Django 6.0 on 2025-12-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("country_interest", models.CharField(max_length=50)),
                ("course_interest", models.CharField(max_length=100)),
                ("ielts_score", models.FloatField(blank=True, null=True)),
                ("budget", models.IntegerField(blank=True, null=True)),
                ("intake", models.CharField(max_length=20)),
                ("lead_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
