# Generated by Django 5.2.9 on 2026-02-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="backlogs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="qualification",
            field=models.CharField(
                choices=[("12th", "12th"), ("Graduation", "Graduation")],
                default="12th",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
