# Generated by Django 5.2.9 on 2026-02-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_lead_backlogs_lead_qualification_alter_lead_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="lead_status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="lead",
            name="recommended_country",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
