# Generated by Django 5.2.11 on 2026-02-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_lead_lead_status_lead_recommended_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="country_interest",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="lead",
            name="course_interest",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
