# Generated by Django 5.2.11 on 2026-02-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_alter_lead_country_interest_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="lead_status",
            new_name="lead_quality",
        ),
        migrations.AddField(
            model_name="lead",
            name="crm_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("followup", "Follow-up"),
                    ("converted", "Converted"),
                    ("lost", "Lost"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
