# Generated by Django 5.2.11 on 2026-02-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_rename_lead_status_lead_lead_quality_lead_crm_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
